add first structure
Ole-Leo/react-music-app pull request #1
Opened 2022-08-24 19:43 UTC by Ole-Leo

Backend
http://51.250.72.80:8090/swagger/  
http://84.201.139.95:8000/swagger/

2022-09-05 16:53 UTC, mrerberg requested changes

2022-09-05 16:53 UTC, mrerberg commented on src/store/tracksAPI.ts
> +import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react';
API файлы рекомендую складывать в папку services/api. Пример структуры можешь посмотреть в шпоре

2022-09-05 16:53 UTC, mrerberg commented on src/store/playerSlice.ts
> +    addTracks: (state, action: PayloadAction<TrackData[]>) => {
А зачем нужен данный экшен?

2022-09-05 16:53 UTC, mrerberg commented on src/store/playerSlice.ts
> +  tracks: [],
Зачем хранить экшены в сторе, если они есть в кеше?

2022-09-12 17:40 UTC, Ole-Leo commented on src/store/tracksAPI.ts
> +import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react';
Окей, поменяю. Пасиб)

2022-09-12 17:41 UTC, Ole-Leo commented on src/store/playerSlice.ts
> +    addTracks: (state, action: PayloadAction<TrackData[]>) => {
чтобы потом реализовать в плеере переключение треков вперёд/назад/ и пр.

2022-09-12 17:43 UTC, Ole-Leo commented on src/store/playerSlice.ts
> +  tracks: [],
тут я тебя не поняла, если честно: выделил кусок стейта, а спрашиваешь, про экшн

2023-02-05 03:50 UTC, closed without merging

2023-02-05 03:50 UTC, Ole-Leo commented
outdated